[project]
name = "quad-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mujoco>=3.3.4",
    "numpy==2.2",
    "pynput>=1.8.1",
    "tensorboard>=2.20.0",
    "wandb>=0.21.0",
]
